@Hotel_HostAddress = https://localhost:7115

GET {{Hotel_HostAddress}}/api/hotel

###

POST {{Hotel_HostAddress}}/api/hotel
Content-Type: application/json

{
  //HotelInfo
}

###

@id=2
DELETE {{Hotel_HostAddress}}/api/hotel/{{id}}

###

GET {{Hotel_HostAddress}}/api/hotel/{{id}}

###

PUT {{Hotel_HostAddress}}/api/hotel/{{id}}
Content-Type: application/json

{
  //HotelInfo
}

###

DELETE {{Hotel_HostAddress}}/api/v1/Hotel?Id={{Id}}

###

DELETE {{Hotel_HostAddress}}/api/v1/Hotel/{{Id}}

###

DELETE {{Hotel_HostAddress}}/api/v1/Hotel/{{Id}}

###
